In [ ]:
from google.colab import files
uploaded = files.upload()

Saving custos_importacao.json to custos_importacao.json

In [ ]:
import pandas as pd
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [ ]:
df_custos = pd.read_json("custos_importacao.json")
print("Tamanho:", df_custos.shape)

✅ Custos carregado!
Tamanho: (150, 4)

In [ ]:
print("Colunas:", df_custos.columns.tolist())
print("\nTipos de dados:")
print(df_custos.dtypes)
print("\nPrimeiras linhas:")
df_custos.head()

Colunas: ['product_id', 'product_name', 'category', 'historic_data']

Tipos de dados:
product_id        int64
product_name     object
category         object
historic_data    object
dtype: object

Primeiras linhas:

,product_id,product_name,category,historic_data
0,1,Transponder AIS Maré Magnum,eletrônicos,"[{'start_date': '10/08/2016', 'usd_price': 105..."
1,2,Transponder Furuno Marlin,eletrônicos,"[{'start_date': '23/11/2017', 'usd_price': 432..."
2,3,Radar Furuno Pulse Leviathan,eletrônicos,"[{'start_date': '12/04/2016', 'usd_price': 254..."
3,4,Rádio AIS Hydro Tidal Zen,eletrônicos,"[{'start_date': '04/03/2016', 'usd_price': 909..."
4,5,Piloto Automático Furuno Storm,eletrônicos,"[{'start_date': '10/02/2016', 'usd_price': 600..."

In [ ]:
resumo_id = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "IDs únicos",
        "IDs nulos",
        "IDs duplicados"
    ],
    "Valor": [
        len(df_custos),
        df_custos["product_id"].nunique(),
        df_custos["product_id"].isnull().sum(),
        df_custos["product_id"].duplicated().sum()
    ]
})
print("TABELA — PRODUCT_ID")
print(resumo_id.to_string(index=False))

🔢 TABELA — PRODUCT_ID
           Métrica  Valor
Total de registros    150
        IDs únicos    150
         IDs nulos      0
    IDs duplicados      0

In [ ]:
resumo_name = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "Nomes únicos",
        "Nomes nulos",
        "Nomes em branco"
    ],
    "Valor": [
        len(df_custos),
        df_custos["product_name"].nunique(),
        df_custos["product_name"].isnull().sum(),
        (df_custos["product_name"].str.strip() == "").sum()
    ]
})
print("TABELA — PRODUCT_NAME")
print(resumo_name.to_string(index=False))

📦 TABELA — PRODUCT_NAME
           Métrica  Valor
Total de registros    150
      Nomes únicos    150
       Nomes nulos      0
   Nomes em branco      0

In [ ]:
resumo_category = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "Categorias únicas",
        "Nulos",
        "Em branco"
    ],
    "Valor": [
        len(df_custos),
        df_custos["category"].nunique(),
        df_custos["category"].isnull().sum(),
        (df_custos["category"].str.strip() == "").sum()
    ]
})
print("TABELA — CATEGORY")
print(resumo_category.to_string(index=False))

print("\nCategorias encontradas:")
print(df_custos["category"].value_counts())

🏷️ TABELA — CATEGORY
           Métrica  Valor
Total de registros    150
 Categorias únicas      3
             Nulos      0
         Em branco      0

Categorias encontradas:
category
eletrônicos    50
propulsão      50
ancoragem      50
Name: count, dtype: int64

In [ ]:
print("TABELA — HISTORIC_DATA")
print("\nTipo da coluna:", df_custos["historic_data"].dtype)
print("\nPrimeiros valores:")
print(df_custos["historic_data"].head(10))
print("\nNulos:", df_custos["historic_data"].isnull().sum())

📊 TABELA — HISTORIC_DATA

Tipo da coluna: object

Primeiros valores:
0    [{'start_date': '10/08/2016', 'usd_price': 105...
1    [{'start_date': '23/11/2017', 'usd_price': 432...
2    [{'start_date': '12/04/2016', 'usd_price': 254...
3    [{'start_date': '04/03/2016', 'usd_price': 909...
4    [{'start_date': '10/02/2016', 'usd_price': 600...
5    [{'start_date': '23/07/2020', 'usd_price': 228...
6    [{'start_date': '26/10/2016', 'usd_price': 625...
7    [{'start_date': '06/12/2019', 'usd_price': 119...
8    [{'start_date': '26/12/2018', 'usd_price': 101...
9    [{'start_date': '29/05/2018', 'usd_price': 859...
Name: historic_data, dtype: object

Nulos: 0

In [ ]:
print(type(df_custos["historic_data"][0]))

<class 'list'>

In [ ]:
import json

# Se estiver como string, converter para lista
df_custos["historic_data"] = df_custos["historic_data"].apply(
    lambda x: json.loads(x) if isinstance(x, str) else x
)

print("Conversão concluída!")
print("Exemplo do primeiro registro:")
print(df_custos["historic_data"][0])

✅ Conversão concluída!
Exemplo do primeiro registro:
[{'start_date': '10/08/2016', 'usd_price': 10583.63}, {'start_date': '15/06/2018', 'usd_price': 8778.36}, {'start_date': '25/09/2018', 'usd_price': 8023.87}, {'start_date': '19/03/2019', 'usd_price': 8772.78}, {'start_date': '17/01/2020', 'usd_price': 7918.18}, {'start_date': '17/06/2020', 'usd_price': 6310.01}, {'start_date': '02/07/2021', 'usd_price': 6586.7}, {'start_date': '16/05/2022', 'usd_price': 6538.2}, {'start_date': '28/02/2023', 'usd_price': 6360.91}, {'start_date': '17/10/2023', 'usd_price': 6574.8}, {'start_date': '16/02/2024', 'usd_price': 6657.12}, {'start_date': '22/02/2024', 'usd_price': 6703.2}, {'start_date': '15/03/2024', 'usd_price': 6633.66}, {'start_date': '02/08/2024', 'usd_price': 5774.5}, {'start_date': '08/04/2025', 'usd_price': 5579.75}]

In [ ]:
def pegar_custo_recente(historico):
    try:
        # Ordenar por data e pegar o mais recente
        ordenado = sorted(historico, key=lambda x: pd.to_datetime(x["start_date"], dayfirst=True))
        return ordenado[-1]["usd_price"]
    except:
        return None

df_custos["custo_atual_usd"] = df_custos["historic_data"].apply(pegar_custo_recente)

print("Custo mais recente extraído!")
print(df_custos[["product_id", "product_name", "custo_atual_usd"]].head())

✅ Custo mais recente extraído!
   product_id                    product_name  custo_atual_usd
0           1     Transponder AIS Maré Magnum         5,579.75
1           2       Transponder Furuno Marlin         2,602.27
2           3    Radar Furuno Pulse Leviathan         1,753.77
3           4       Rádio AIS Hydro Tidal Zen           583.85
4           5  Piloto Automático Furuno Storm         4,285.30

In [ ]:
registros = []

for _, row in df_custos.iterrows():
    for entrada in row["historic_data"]:
        registros.append({
            "product_id": row["product_id"],
            "product_name": row["product_name"],
            "category": row["category"],
            "start_date": entrada["start_date"],
            "usd_price": entrada["usd_price"]
        })

df_custos_expandido = pd.DataFrame(registros)
df_custos_expandido["start_date"] = pd.to_datetime(
    df_custos_expandido["start_date"], dayfirst=True
)

print("Histórico expandido!")
print("Total de registros:", len(df_custos_expandido))
df_custos_expandido.head()

✅ Histórico expandido!
Total de registros: 1260

   product_id                 product_name     category start_date  usd_price
0           1  Transponder AIS Maré Magnum  eletrônicos 2016-08-10  10,583.63
1           1  Transponder AIS Maré Magnum  eletrônicos 2018-06-15   8,778.36
2           1  Transponder AIS Maré Magnum  eletrônicos 2018-09-25   8,023.87
3           1  Transponder AIS Maré Magnum  eletrônicos 2019-03-19   8,772.78
4           1  Transponder AIS Maré Magnum  eletrônicos 2020-01-17   7,918.18

In [ ]:
resumo_custos = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "Produtos únicos",
        "Data mais antiga",
        "Data mais recente",
        "Custo mínimo (USD)",
        "Custo máximo (USD)",
        "Custo médio (USD)"
    ],
    "Valor": [
        len(df_custos_expandido),
        df_custos_expandido["product_id"].nunique(),
        df_custos_expandido["start_date"].min().strftime("%d/%m/%Y"),
        df_custos_expandido["start_date"].max().strftime("%d/%m/%Y"),
        f"$ {df_custos_expandido['usd_price'].min():,.2f}",
        f"$ {df_custos_expandido['usd_price'].max():,.2f}",
        f"$ {df_custos_expandido['usd_price'].mean():,.2f}"
    ]
})

print("TABELA — CUSTOS DE IMPORTAÇÃO")
print(resumo_custos.to_string(index=False))

💰 TABELA — CUSTOS DE IMPORTAÇÃO
           Métrica       Valor
Total de registros        1260
   Produtos únicos         150
  Data mais antiga  04/01/2016
 Data mais recente  31/12/2025
Custo mínimo (USD)     $ 53.37
Custo máximo (USD) $ 48,583.21
 Custo médio (USD)  $ 7,890.23

In [ ]:
# Versão resumida com custo atual
df_custos[["product_id", "product_name", "category", "custo_atual_usd"]].to_csv(
    "custos_resumido.csv", index=False
)

# Versão expandida com todo o histórico
df_custos_expandido.to_csv("custos_expandido.csv", index=False)

print("Bases de custos salvas!")

✅ Bases de custos salvas!