In [ ]:
from google.colab import files
uploaded = files.upload()

Saving vendas_2023_2024.csv to vendas_2023_2024.csv

In [ ]:
import pandas as pd
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")
df = pd.read_csv("vendas_2023_2024.csv")

In [ ]:
print("Tamanho:", df.shape)
print("\nColunas:", df.columns.tolist())
print("\nTipos de dados:")
print(df.dtypes)
print("\nPrimeiras linhas:")
df.head()

Tamanho: (9895, 6)

Colunas: ['id', 'id_client', 'id_product', 'qtd', 'total', 'sale_date']

Tipos de dados:
id              int64
id_client       int64
id_product      int64
qtd             int64
total         float64
sale_date      object
dtype: object

Primeiras linhas:

   id  id_client  id_product  qtd      total   sale_date
0   0         42         105   11   3,405.00  2023-09-10
1   1          3         136    9  16,873.90  15-09-2024
2   2         25         139    7   9,475.30  2024-08-13
3   4         20          23    5  55,893.00  2023-02-03
4   5          8          57    4 451,403.90  2024-02-12

In [ ]:
print("Valores nulos:")
print(df.isnull().sum())

print("\nDuplicatas:", df.duplicated().sum())

Valores nulos:
id            0
id_client     0
id_product    0
qtd           0
total         0
sale_date     0
dtype: int64

Duplicatas: 0

In [ ]:
df.describe()

            id  id_client  id_product      qtd        total
count 9,895.00   9,895.00    9,895.00 9,895.00     9,895.00
mean  5,000.76      24.87       75.26     8.02   263,797.83
std   2,887.00      14.18       43.53     4.30   390,007.18
min       0.00       1.00        1.00     1.00       294.50
25%   2,501.50      13.00       37.00     4.00    23,138.20
50%   4,999.00      25.00       74.00     8.00    82,225.00
75%   7,505.50      37.00      114.00    12.00   339,094.50
max   9,999.00      49.00      150.00    15.00 2,222,973.00

In [ ]:
# Período coberto pelas vendas
print("Data mais antiga:", df["sale_date"].min())
print("Data mais recente:", df["sale_date"].max())

# Quantidade vendida
print("\nEstatísticas de quantidade:")
print(df["qtd"].describe())

# Quantidade total vendida
print("\nEstatísticas de total:")
print(df["total"].describe())

# Quantos clientes únicos
print("\nClientes únicos:", df["id_client"].nunique())

# Quantos produtos únicos vendidos
print("\nProdutos únicos:", df["id_product"].nunique())

Data mais antiga: 01-01-2023
Data mais recente: 31-12-2024

Estatísticas de quantidade:
count   9,895.00
mean        8.02
std         4.30
min         1.00
25%         4.00
50%         8.00
75%        12.00
max        15.00
Name: qtd, dtype: float64

Estatísticas de total:
count       9,895.00
mean      263,797.83
std       390,007.18
min           294.50
25%        23,138.20
50%        82,225.00
75%       339,094.50
max     2,222,973.00
Name: total, dtype: float64

Clientes únicos: 49

Produtos únicos: 150

In [ ]:
resumo_qtd = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "Quantidade mínima",
        "Quantidade máxima",
        "Média",
        "Zeros",
        "Negativos"
    ],
    "Valor": [
        len(df),
        df["qtd"].min(),
        df["qtd"].max(),
        round(df["qtd"].mean(), 2),
        (df["qtd"] == 0).sum(),
        (df["qtd"] < 0).sum()
    ]
})

print("TABELA — QUANTIDADE (qtd)")
print(resumo_qtd.to_string(index=False))

📦 TABELA — QUANTIDADE (qtd)
           Métrica    Valor
Total de registros 9,895.00
 Quantidade mínima     1.00
 Quantidade máxima    15.00
             Média     8.02
             Zeros     0.00
         Negativos     0.00

In [ ]:
resumo_total = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "Valor mínimo",
        "Valor máximo",
        "Média",
        "Soma total (faturamento)",
        "Zeros",
        "Negativos"
    ],
    "Valor": [
        len(df),
        df["total"].min(),
        df["total"].max(),
        round(df["total"].mean(), 2),
        round(df["total"].sum(), 2),
        (df["total"] == 0).sum(),
        (df["total"] < 0).sum()
    ]
})

print("TABELA — VALOR TOTAL (total)")
print(resumo_total.to_string(index=False))

💰 TABELA — VALOR TOTAL (total)
                 Métrica            Valor
      Total de registros         9,895.00
            Valor mínimo           294.50
            Valor máximo     2,222,973.00
                   Média       263,797.83
Soma total (faturamento) 2,610,279,510.70
                   Zeros             0.00
               Negativos             0.00

In [ ]:
ranking = df.groupby("id_product").agg(
    total_qtd=("qtd", "sum"),
    total_faturado=("total", "sum")
).reset_index().sort_values("total_faturado", ascending=False)

print("\n Top 10 produtos — quantidade e valor:")
print(ranking.head(10).to_string(index=False))

🏆 Top 10 produtos — quantidade e valor:
 id_product  total_qtd  total_faturado
         76        578   83,539,339.40
         71        641   81,567,066.65
         73        497   69,554,254.80
         63        505   68,817,185.90
         80        533   67,332,086.05
         91        506   66,829,268.70
         54        556   65,859,716.10
         81        538   64,195,127.60
         72        647   63,057,815.65
         55        569   61,224,375.00

In [ ]:
resumo_clientes = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "Clientes únicos",
        "Clientes nulos",
        "Média de compras por cliente"
    ],
    "Valor": [
        len(df),
        df["id_client"].nunique(),
        df["id_client"].isnull().sum(),
        round(df.groupby("id_client").size().mean(), )
    ]
})

print("TABELA — CLIENTES")
print(resumo_clientes.to_string(index=False))

👥 TABELA — CLIENTES
                     Métrica  Valor
          Total de registros   9895
             Clientes únicos     49
              Clientes nulos      0
Média de compras por cliente    202

In [ ]:
resumo_produtos = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "Produtos únicos vendidos",
        "Produtos nulos",
        "Produto mais vendido (id)"
    ],
    "Valor": [
        len(df),
        df["id_product"].nunique(),
        df["id_product"].isnull().sum(),
        df["id_product"].value_counts().idxmax()
    ]
})

print("TABELA — PRODUTOS")
print(resumo_produtos.to_string(index=False))

📦 TABELA — PRODUTOS
                  Métrica  Valor
       Total de registros   9895
 Produtos únicos vendidos    150
           Produtos nulos      0
Produto mais vendido (id)    116

In [ ]:
df["sale_date"] = pd.to_datetime(df["sale_date"], format='mixed', dayfirst=True)

resumo_datas = pd.DataFrame({
    "Métrica": [
        "Total de registros",
        "Data mais antiga",
        "Data mais recente",
        "Período coberto (dias)",
        "Datas nulas"
    ],
    "Valor": [
        len(df),
        df["sale_date"].min().strftime("%d/%m/%Y"),
        df["sale_date"].max().strftime("%d/%m/%Y"),
        (df["sale_date"].max() - df["sale_date"].min()).days,
        df["sale_date"].isnull().sum()
    ]
})

print("TABELA — DATAS")
print(resumo_datas.to_string(index=False))

📅 TABELA — DATAS
               Métrica      Valor
    Total de registros       9895
      Data mais antiga 01/01/2023
     Data mais recente 31/12/2024
Período coberto (dias)        730
           Datas nulas          0

In [ ]:
print("Duplicatas antes:", df.duplicated().sum())
df = df.drop_duplicates()
print("Duplicatas depois:", df.duplicated().sum())

Duplicatas antes: 0
Duplicatas depois: 0

In [ ]:
print("Nulos por coluna:")
print(df.isnull().sum())

# Remover linhas sem id, id_client ou id_product
df = df.dropna(subset=["id", "id_client", "id_product"])

# Remover linhas sem data
df = df.dropna(subset=["sale_date"])

Nulos por coluna:
id            0
id_client     0
id_product    0
qtd           0
total         0
sale_date     0
dtype: int64

In [ ]:
# Garantir que a data está no formato correto
df["sale_date"] = pd.to_datetime(df["sale_date"])

# Garantir que qtd e total são números
df["qtd"] = pd.to_numeric(df["qtd"], errors="coerce")
df["total"] = pd.to_numeric(df["total"], errors="coerce")

# Garantir que ids são inteiros
df["id"] = df["id"].astype(int)
df["id_client"] = df["id_client"].astype(int)
df["id_product"] = df["id_product"].astype(int)

In [ ]:
# Garantir que a data está no formato correto
df["sale_date"] = pd.to_datetime(df["sale_date"])

# Garantir que qtd e total são números
df["qtd"] = pd.to_numeric(df["qtd"], errors="coerce")
df["total"] = pd.to_numeric(df["total"], errors="coerce")

# Garantir que ids são inteiros
df["id"] = df["id"].astype(int)
df["id_client"] = df["id_client"].astype(int)
df["id_product"] = df["id_product"].astype(int)

In [ ]:
print("Data mais antiga:", df["sale_date"].min().strftime("%d/%m/%Y"))
print("Data mais recente:", df["sale_date"].max().strftime("%d/%m/%Y"))

# Remover datas fora do período esperado (2023-2024)
df = df[df["sale_date"].dt.year.isin([2023, 2024])]
print("Registros após filtro de período:", len(df))

Data mais antiga: 01/01/2023
Data mais recente: 31/12/2024
Registros após filtro de período: 9895

In [ ]:
df.to_csv("vendas_limpo.csv", index=False)

✅ Base de vendas limpa salva!